services:

  user-db:
    image: postgres:16
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123456
    ports:
      - "5433:5432"
    volumes:
      - user_data:/var/lib/postgresql/data

  product-db:
    image: postgres:16
    environment:
      POSTGRES_DB: product_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123456
    ports:
      - "5434:5432"
    volumes:
      - product_data:/var/lib/postgresql/data

  orders-db:
    image: postgres:16
    environment:
      POSTGRES_DB: orders_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123456
    ports:
      - "5435:5432"
    volumes:
      - orders_data:/var/lib/postgresql/data

  user-service:
    image: user-service
    ports:
      - "8081:8080"
    depends_on:
      - user-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/user_service
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123456

  product-service:
    image: product-service
    ports:
      - "8082:8080"
    depends_on:
      - product-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-db:5432/product_service
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123456



volumes:
  user_data:
  product_data:
  orders_data:
